//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Cxbx.rc
//
#define IDI_CXBX                        101
#define IDB_SPLASH                      102
#define IDR_MAINMENU                    103
#define IDB_LOGO                        106
#define IDB_ABOUT                       108
#define IDD_INPUT_CFG                   111
#define IDD_LOGGING_CFG                 112
#define IDD_VIDEO_CFG                   113
#define IDD_AUDIO_CFG                   114
#define IDD_EEPROM_CFG                  115
#define IDR_JPEG_ABOUT                  116
#define IDR_JPEG_SPLASH                 118
#define IDD_ABOUT                       119
#define IDR_CONTRIBUTORS                121
#define IDR_COPYING                     122
#define IDD_VIRTUAL_SBC_FEEDBACK        133
#define IDD_XID_DUKE_CFG                134
#define IDD_RUMBLE_CFG                  135
#define IDD_NETWORK_CFG                 136
#define IDC_LOG_CANCEL                  892
#define IDC_LOG_ACCEPT                  893
#define IDC_LOG_ENABLE_GENERAL          894
#define IDC_LOG_DISABLE_GENERAL         895
#define IDC_LOG_ENABLE_KERNEL           896
#define IDC_LOG_DISABLE_KERNEL          897
#define IDC_LOG_CUSTOM_GENERAL          898
#define IDC_LOG_CUSTOM_KERNEL           899
#define IDC_LOG_CXBXR                   900
#define IDC_LOG_XBE                     901
#define IDC_LOG_INIT                    902
#define IDC_LOG_VMEM                    903
#define IDC_LOG_PMEM                    904
#define IDC_LOG_GUI                     905
#define IDC_LOG_EEPR                    906
#define IDC_LOG_RSA                     907
#define IDC_LOG_POOLMEM                 908
#define IDC_LOG_D3D8                    909
#define IDC_LOG_D3DST                   910
#define IDC_LOG_D3DCVT                  911
#define IDC_LOG_DSOUND                  912
#define IDC_LOG_XAPI                    913
#define IDC_LOG_XACT                    914
#define IDC_LOG_XGRP                    915
#define IDC_LOG_XONLINE                 916
#define IDC_LOG_FS                      917
#define IDC_LOG_PSHB                    918
#define IDC_LOG_PXSH                    919
#define IDC_LOG_VTXSH                   920
#define IDC_LOG_VTXB                    921
#define IDC_LOG_DINP                    922
#define IDC_LOG_XINP                    923
#define IDC_LOG_SDL                     924
#define IDC_LOG_FILE                    925
#define IDC_LOG_X86                     926
#define IDC_LOG_HLE                     927
#define IDC_LOG_NET                     928
#define IDC_LOG_MCPX                    929
#define IDC_LOG_NV2A                    930
#define IDC_LOG_SMC                     931
#define IDC_LOG_OHCI                    932
#define IDC_LOG_USB                     933
#define IDC_LOG_HUB                     934
#define IDC_LOG_XIDCTRL                 935
#define IDC_LOG_ADM                     936
#define IDC_LOG_KRNL                    937
#define IDC_LOG_LOG                     938
#define IDC_LOG_XBOX                    939
#define IDC_LOG_XBDM                    940
#define IDC_LOG_AV                      941
#define IDC_LOG_DBG                     942
#define IDC_LOG_EX                      943
#define IDC_LOG_FSC                     944
#define IDC_LOG_HAL                     945
#define IDC_LOG_IO                      946
#define IDC_LOG_KD                      947
#define IDC_LOG_KE                      948
#define IDC_LOG_KI                      949
#define IDC_LOG_MM                      950
#define IDC_LOG_NT                      951
#define IDC_LOG_OB                      952
#define IDC_LOG_PS                      953
#define IDC_LOG_RTL                     954
#define IDC_LOG_XC                      955
#define IDC_LOG_XE                      956
#define IDC_LOG_INPSYS                  957
#define IDC_LOG_DSBUFFER                958
#define IDC_LOG_DSSTREAM                959
#define IDC_LOG_DS3DCALC                960
#define IDC_LOG_XMO                     961
#define IDC_LOG_VSHCACHE                962
#define IDC_SET_MOTOR                   999
#define IDC_SET_X                       1000
#define IDC_SET_Y                       1001
#define IDC_SET_A                       1002
#define IDC_SET_B                       1003
#define IDC_SET_WHITE                   1004
#define IDC_SET_BLACK                   1005
#define IDC_SET_LTRIGGER                1006
#define IDC_SET_RTRIGGER                1007
#define IDC_SET_LTHUMB                  1008
#define IDC_SET_RTHUMB                  1009
#define IDC_SET_START                   1010
#define IDC_SET_BACK                    1011
#define IDC_SET_DPAD_LEFT               1012
#define IDC_SET_DPAD_RIGHT              1013
#define IDC_SET_DPAD_UP                 1014
#define IDC_SET_DPAD_DOWN               1015
#define IDC_SET_LEFT_POSY               1016
#define IDC_SET_LEFT_NEGX               1017
#define IDC_SET_LEFT_NEGY               1018
#define IDC_SET_LEFT_POSX               1019
#define IDC_INPUT_CONFIG_CANCEL         1020
#define IDC_INPUT_CONFIG_ACCEPT         1021
#define IDC_CONFIG_STATUS               1022
#define IDC_SET_RIGHT_POSY              1023
#define IDC_SET_RIGHT_NEGY              1024
#define IDC_SET_RIGHT_NEGX              1025
#define IDC_SET_RIGHT_POSX              1026
#define IDC_CONFIGURE_ALL               1027
#define IDC_BTN_EJECT                   1028
#define IDC_BTN_COCKPIT_HATCH           1029
#define IDC_BTN_IGNITION                1030
#define IDC_BTN_START                   1031
#define IDC_CV_FULLSCREEN               1032
#define IDC_BTN_ZOOM_IN                 1033
#define IDC_BTN_ZOOM_OUT                1034
#define IDC_BTN_MODE_SELECT             1035
#define IDC_VC_DISPLAY_ADAPTER          1036
#define IDC_BTN_SUB_MONITOR_MODE_SELECT 1037
#define IDC_VC_D3D_DEVICE               1038
#define IDC_BTN_OPEN_CLOSE              1039
#define IDC_BTN_MAP_ZOON_IN_OUT         1040
#define IDC_VC_ACCEPT                   1041
#define IDC_BTN_MAIN_WEAPON_CONTROL     1042
#define IDC_VC_CANCEL                   1043
#define IDC_BTN_SUB_WEAPON_CONTROL      1044
#define IDC_CV_VSYNC                    1045
#define IDC_BTN_EXTINGUISHER            1046
#define IDC_BTN_MAGAZINE_CHANGE         1047
#define IDC_BTN_CHAFF                   1048
#define IDC_BTN_WASHING                 1049
#define IDC_BTN_COM1                    1050
#define IDC_VC_VIDEO_RESOLUTION         1051
#define IDC_BTN_COM2                    1052
#define IDC_VC_RENDER_RESOLUTION        1052
#define IDC_BTN_COM3                    1053
#define IDC_BTN_COM4                    1054
#define IDC_CV_HARDWAREYUV              1055
#define IDC_BTN_COM5                    1056
#define IDC_BTN_FUNC1                   1057
#define IDC_BTN_FUNC2                   1058
#define IDC_BTN_FUNC3                   1059
#define IDC_BTN_TANK_DETACH             1060
#define IDC_LIST2                       1061
#define IDC_BTN_FSS                     1062
#define IDC_ABOUT                       1063
#define IDC_BTN_OVERRIDE                1064
#define IDC_TAB1                        1065
#define IDC_BTN_NIGHT_SCOPE             1066
#define IDC_AC_ACCEPT                   1067
#define IDC_BTN_MANIPULATOR             1068
#define IDC_AC_CANCEL                   1069
#define IDC_BTN_LINE_COLOR_CHANGE       1070
#define IDC_AC_AUDIO_ADAPTER            1071
#define IDC_AC_PCM                      1072
#define IDC_AC_XADPCM                   1073
#define IDC_AC_UNKNOWN_CODEC            1074
#define IDC_EE_CONFOUNDER               1075
#define IDC_EE_HDDKEY                   1076
#define IDC_EE_XBOX_REGION              1077
#define IDC_EE_SERIAL_NUMBER            1078
#define IDC_EE_MAC_ADDRESS              1079
#define IDC_EE_ONLINE_KEY               1080
#define IDC_EE_AVREGION                 1081
#define IDC_EE_LANGUAGE                 1082
#define IDC_EE_AVSETTINGS               1083
#define IDC_EE_AUDIOSETTINGS            1084
#define IDC_EE_GAME_PRTL_CRTL           1085
#define IDC_EE_PRTL_PASS                1086
#define IDC_EE_MOVIE_PRTL_CRTL          1087
#define IDC_EE_DVDREGION                1088
#define IDC_EE_ACCEPT                   1089
#define IDC_EE_CANCEL                   1090
#define IDC_EE_RESET                    1091
#define IDC_EE_PAL60HZ                  1092
#define IDC_EE_480P                     1093
#define IDC_EE_720P                     1094
#define IDC_EE_1080I                    1095
#define ID_GUI_STATUS_KRNL_IS_READY     1096
#define ID_GUI_STATUS_LLE_FLAGS         1097
#define ID_GUI_STATUS_XBOX_LED_COLOUR   1098
#define ID_GUI_STATUS_LOG_ENABLED       1099
#define IDC_AC_MUTE_WHEN_UNFOCUS        1100
#define IDC_XBOX_PORT_0                 1158
#define IDC_XBOX_PORT_1                 1166
#define IDC_XBOX_PORT_2                 1174
#define IDC_XBOX_PORT_3                 1182
#define IDC_LEFTBLOCK                   1200
#define IDC_LEFTBLOCK2                  1201
#define IDC_RIGHTBLOCK                  1202
#define IDC_GEAR_LEVER                  1203
#define IDC_GEAR_0                      1204
#define IDC_GEAR_1                      1205
#define IDC_GEAR_2                      1206
#define IDC_GEAR_3                      1207
#define IDC_GEAR_4                      1208
#define IDC_GEAR_5                      1209
#define IDC_GEAR_R                      1210
#define IDC_ROTATION_LEVER              1211
#define IDC_TXT_ROTATION_LEVER          1212
#define IDC_VT_LOCATION_MEASUREMENT     1213
#define IDC_BUFFER_MATERIAL             1214
#define IDC_FUEL_FLOW_RATE              1215
#define IDC_OXYGEN_SUPPLY_SYSTEM        1216
#define IDC_FILT_CONTROL_SYSTEM         1217
#define IDC_PB_EJECT                    1218
#define IDC_PB_COCKPIT_HATCH            1219
#define IDC_PB_IGNITION                 1220
#define IDC_PB_START                    1221
#define IDC_PB_GEARLEVER_5              1222
#define IDC_PB_GEARLEVER_1              1223
#define IDC_PB_GEARLEVER_2              1224
#define IDC_PB_GEARLEVER_3              1225
#define IDC_PB_GEARLEVER_4              1226
#define IDC_PB_GEARLEVER_N              1227
#define IDC_PB_GEARLEVER_R              1228
#define IDC_PB_COM5                     1229
#define IDC_PB_COM1                     1230
#define IDC_PB_COM2                     1231
#define IDC_PB_COM3                     1232
#define IDC_PB_COM4                     1233
#define IDC_PB_WASHING                  1234
#define IDC_PB_MAIN_WEAPON_CONTROL      1235
#define IDC_PB_EXTINGUISHER             1236
#define IDC_PB_SUB                      1237
#define IDC_PB_SUB_WEAPON_CONTROL       1237
#define IDC_PB_CHAFF                    1238
#define IDC_PB_MAGAZINE_CHANGE          1239
#define IDC_PB_FUNC1                    1240
#define IDC_PB_FUNC2                    1241
#define IDC_PB_FUNC3                    1242
#define IDC_PB_TANK_DETACH              1243
#define IDC_PB_OVERRIDE                 1244
#define IDC_PB_NIGHT_SCOPE              1245
#define IDC_PB_FSS                      1246
#define IDC_PB_MANIPULATOR              1247
#define IDC_PB_LINE_COLOR_CHANGE        1248
#define IDC_PB_OPEN_CLOSE               1249
#define IDC_PB_MAP_ZOOM_IN_OUT          1250
#define IDC_PB_ZOOM_IN                  1251
#define IDC_PB_ZOOM_OUT                 1252
#define IDC_PB_MODE_SELECT              1253
#define IDC_PB_SUB_MONITOR_MODE_SELECT  1254
#define IDC_RADIO_TD0                   1255
#define IDC_RADIO_TD1                   1256
#define IDC_RADIO_TD2                   1257
#define IDC_RADIO_TD3                   1258
#define IDC_RADIO_TD4                   1259
#define IDC_RADIO_TD5                   1260
#define IDC_RADIO_TD6                   1261
#define IDC_RADIO_TD7                   1262
#define IDC_RADIO_TD8                   1263
#define IDC_RADIO_TD9                   1264
#define IDC_RADIO_TD10                  1265
#define IDC_RADIO_TD11                  1266
#define IDC_RADIO_TD12                  1267
#define IDC_PB_VT_LOCATION_MEASUREMENT  1268
#define IDC_PB_OXYGEN_SUPPLY_SYSTEM     1269
#define IDC_PB_BUFFER_MATERIAL          1270
#define IDC_PB_VT_LOCATION_MEASUREMENT4 1271
#define IDC_PB_FILT_CONTROL_SYSTEM      1272
#define IDC_EVENT_LV                    1273
#define IDC_CXBXR_EVENTS                1274
#define IDC_KERNEL_EVENTS               1275
#define IDC_XID_CONFIG                  1276
#define IDC_DEVICE_PORT1                1277
#define IDC_DEVICE_PORT2                1278
#define IDC_DEVICE_PORT3                1279
#define IDC_DEVICE_PORT4                1280
#define IDC_CONFIGURE_PORT1             1281
#define IDC_CONFIGURE_PORT2             1282
#define IDC_CONFIGURE_PORT3             1283
#define IDC_CONFIGURE_PORT4             1284
#define IDC_DEVICE_LIST                 1285
#define IDC_REFRESH_DEVICES             1286
#define IDC_XID_DEFAULT                 1287
#define IDC_XID_PROFILE                 1288
#define IDC_XID_PROFILE_NAME            1289
#define IDC_XID_PROFILE_SAVE            1291
#define IDC_XID_PROFILE_DELETE          1292
#define IDC_XID_BUTTONS                 1293
#define IDC_XID_LSTICK                  1294
#define IDC_XID_RSTICK                  1295
#define IDC_XID_DPAD                    1296
#define IDC_XID_TRIGGERS                1297
#define IDC_XID_RUMBLE                  1298
#define IDC_XID_OPTIONS                 1299
#define IDC_XID_CLEAR                   1300
#define IDC_RUMBLE_LIST                 1301
#define IDC_RUMBLE_TEST                 1302
#define IDC_NETWORK_ADAPTER             1303
#define IDC_LOG_POPUP_TESTCASE          1304
#define ID_FILE_EXIT                    40005
#define ID_HELP_ABOUT                   40008
#define ID_EMULATION_START              40009
#define ID_FILE_OPEN_XBE                40013
#define ID_FILE_CLOSE_XBE               40014
#define ID_FILE_OPEN_DASHBOARD          40015
#define ID_HELP_HOMEPAGE                40019
#define ID_FILE_SAVEXBEFILE             40021
#define ID_FILE_SAVEXBEFILEAS           40022
#define ID_EDIT_LOGOBITMAP_EXPORT       40025
#define ID_EDIT_LOGOBITMAP_IMPORT       40026
#define ID_EDIT_PATCH_ALLOW64MB         40027
#define ID_EDIT_PATCH_DEBUGMODE         40031
#define ID_EMULATION_DEBUGOUTPUTGUI_CONSOLE 40035
#define ID_EMULATION_DEBUGOUTPUTGUI_FILE 40036
#define ID_EMULATION_DEBUGOUTPUTKERNEL_CONSOLE 40037
#define ID_EMULATION_DEBUGOUTPUTKERNEL_FILE 40038
#define ID_EMULATION_LLE_APU            40039
#define ID_EMULATION_LLE_GPU            40040
#define ID_EMULATION_LLE_JIT            40041
#define ID_SETTINGS_CONFIG_INPUT        40046
#define ID_SETTINGS_CONFIG_VIDEO        40047
#define ID_SETTINGS_CONFIG_AUDIO        40048
#define ID_SETTINGS_CONFIG_EEPROM       40049
#define ID_FILE_RXBE_0                  40050
#define ID_FILE_RXBE_1                  40051
#define ID_FILE_RXBE_2                  40052
#define ID_FILE_RXBE_3                  40053
#define ID_FILE_RXBE_4                  40054
#define ID_FILE_RXBE_5                  40055
#define ID_FILE_RXBE_6                  40056
#define ID_FILE_RXBE_7                  40057
#define ID_FILE_RXBE_8                  40058
#define ID_FILE_RXBE_9                  40059
#define ID_EDIT_DUMPXBEINFOTO_FILE      40071
#define ID_EDIT_DUMPXBEINFOTO_DEBUGCONSOLE 40072
#define ID_EMULATION_STOP               40082
#define ID_SETTINGS_CACHE               40083
#define ID_CACHE_CLEARHLECACHE_ALL      40084
#define ID_CACHE_CLEARHLECACHE_CURRENT  40085
#define ID_SETTINGS_HACKS               40088
#define ID_HACKS_DISABLEPIXELSHADERS    40089
#define ID_LED                          40090
#define ID_SETTINGS_INITIALIZE          40091
#define ID_EMULATION_STARTDEBUGGER      40092
#define ID_FPS                          40096
#define ID_HACKS_RUNXBOXTHREADSONALLCORES 40098
#define ID_HACKS_SKIPRDTSCPATCHING      40099
#define ID_HACKS_SPEEDHACKS             40103
#define ID_SETTINGS_CONFIG_DLOCCUSTOM   40104
#define ID_SETTINGS_CONFIG_DLOCAPPDATA  40105
#define ID_SETTINGS_CONFIG_DLOCEXECDIR  40106
#define ID_SETTINGS_ALLOWADMINPRIVILEGE 40107
#define ID_SETTINGS_CONFIG_LOGGING      40108
#define ID_SYNC_CONFIG_LOGGING          40109
#define ID_LOG                          40110
#define ID_SETTINGS_CONFIG_NETWORK      40111
#define ID_SYNC_CONFIG_INPUT            40112
#define ID_SETTINGS_EXPERIMENTAL        40113
#define ID_USELOADEREXEC                40114
#define ID_SETTINGS_IGNOREINVALIDXBESIG 40115
#define ID_SETTINGS_IGNOREINVALIDXBESEC 40116
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40117
#define _APS_NEXT_CONTROL_VALUE         1305
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
