//------------------------------------------------------------------------------
// File: StrmIf.idl
//
// Desc: ActiveMovie interface definitions.
//
// Copyright (c) 1992 - 2000, Microsoft Corporation.  All rights reserved.
//------------------------------------------------------------------------------


import "unknwn.idl";
import "objidl.idl";	// for IPersist (IFilter's root)

#include "devenum.idl"

// core interfaces
#include "axcore.idl"

// extended, ActiveMovie-only interfaces
#include "axextend.idl"

// ActiveMovie-only sample plug-in distributor interface
#include "IAMovie.idl"

// application interfaces for DVD
#include "dvdif.idl"

// Dynamic graph stuff
#include "dyngraph.idl"
