name: Issue
description: Template for issues.
body:
  - type: markdown
    attributes:
      value: |
        Please read https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md and https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ) before opening an issue.
        Remember, the GitHub Issue Tracker is not the place to ask for support. You must use our Discord server https://discord.gg/26Xjx23 for that.
        Compatibility Reports should be submitted at the website: https://cxbx-reloaded.co.uk
        Otherwise, for any other emulation/general issues like crashes when a controller is connected, or regressions across several titles, feel free to report your issue here.
  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      options:
      - label: I've read the [README](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)).
        required: true
      - label: This isn't a game compatibility report.
        required: true
  - type: input
    id: quick-summary
    attributes:
      label: Quick summary
      description: Please briefly describe what isn't working correctly.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please describe the problem as accurately as possible.
    validations:
      required: true
  - type: textarea
    id: system-config
    attributes:
      label: System Configuration
      description: Please your system configuration.
      placeholder: OS, CPU, GPU, etc.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information 
      description: Anything else you deem to be important.
