//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by c:\Users\Aaron\source\repos\cxbx-reloaded2\resource\Cxbx.rc
//
#define IDI_CXBX                        101
#define IDB_SPLASH                      102
#define IDR_MAINMENU                    103
#define IDB_LOGO                        106
#define IDB_ABOUT                       108
#define IDD_CONTROLLER_CFG              111
#define IDD_VIDEO_CFG                   113
#define IDD_AUDIO_CFG                   114
#define IDD_EEPROM_CFG                  115
#define IDR_JPEG_ABOUT                  116
#define IDR_JPEG_SPLASH                 118
#define IDD_ABOUT                       119
#define IDR_CONTRIBUTORS                121
#define IDR_COPYING                     122
#define IDS_UEM                         123
#define IDD_CONTROLLER_HOST_MAPPING     131
#define IDD_VIRTUAL_SBC_FEEDBACK        133
#define IDC_SET_X                       1000
#define IDC_SET_Y                       1001
#define IDC_SET_A                       1002
#define IDC_SET_B                       1003
#define IDC_SET_WHITE                   1004
#define IDC_SET_BLACK                   1005
#define IDC_SET_LTRIGGER                1006
#define IDC_SET_RTRIGGER                1007
#define IDC_SET_LTHUMB                  1008
#define IDC_SET_RTHUMB                  1009
#define IDC_SET_START                   1010
#define IDC_SET_BACK                    1011
#define IDC_SET_DPAD_LEFT               1012
#define IDC_SET_DPAD_RIGHT              1013
#define IDC_SET_DPAD_UP                 1014
#define IDC_SET_DPAD_DOWN               1015
#define IDC_SET_LEFT_POSY               1016
#define IDC_SET_LEFT_NEGX               1017
#define IDC_SET_LEFT_NEGY               1018
#define IDC_SET_LEFT_POSX               1019
#define IDC_INPUT_CONFIG_CANCEL         1022
#define IDC_INPUT_CONFIG_ACCEPT         1023
#define IDC_CONFIG_STATUS               1025
#define IDC_SET_RIGHT_POSY              1026
#define IDC_SET_RIGHT_NEGY              1027
#define IDC_SET_RIGHT_NEGX              1028
#define IDC_SET_RIGHT_POSX              1029
#define IDC_BUTTON1                     1030
#define IDC_CONFIGURE_ALL               1030
#define IDC_BTN_EJECT                   1030
#define IDC_BUTTON2                     1031
#define IDC_BTN_COCKPIT_HATCH           1031
#define IDC_BTN_IGNITION                1032
#define IDC_BTN_START                   1033
#define IDC_CV_FULLSCREEN               1034
#define IDC_BTN_ZOOM_IN                 1034
#define IDC_BTN_ZOOM_OUT                1035
#define IDC_BTN_MODE_SELECT             1036
#define IDC_VC_DISPLAY_ADAPTER          1037
#define IDC_BTN_SUB_MONITOR_MODE_SELECT 1037
#define IDC_VC_D3D_DEVICE               1038
#define IDC_BTN_OPEN_CLOSE              1038
#define IDC_BTN_MAP_ZOON_IN_OUT         1039
#define IDC_VC_ACCEPT                   1040
#define IDC_BTN_MAIN_WEAPON_CONTROL     1040
#define IDC_VC_CANCEL                   1041
#define IDC_BTN_SUB_WEAPON_CONTROL      1041
#define IDC_CV_VSYNC                    1042
#define IDC_BTN_EXTINGUISHER            1042
#define IDC_BTN_MAGAZINE_CHANGE         1043
#define IDC_BTN_CHAFF                   1044
#define IDC_BTN_WASHING                 1045
#define IDC_BTN_COM1                    1046
#define IDC_VC_VIDEO_RESOLUTION         1047
#define IDC_BTN_COM2                    1047
#define IDC_BTN_COM3                    1048
#define IDC_BTN_COM4                    1049
#define IDC_CV_HARDWAREYUV              1050
#define IDC_BTN_COM5                    1050
#define IDC_BTN_FUNC1                   1051
#define IDC_BTN_FUNC2                   1052
#define IDC_BTN_FUNC3                   1053
#define IDC_BTN_TANK_DETACH             1054
#define IDC_LIST2                       1055
#define IDC_BTN_FSS                     1055
#define IDC_ABOUT                       1056
#define IDC_BTN_OVERRIDE                1056
#define IDC_TAB1                        1057
#define IDC_BTN_NIGHT_SCOPE             1057
#define IDC_AC_ACCEPT                   1058
#define IDC_BTN_MANIPULATOR             1058
#define IDC_AC_CANCEL                   1059
#define IDC_BTN_LINE_COLOR_CHANGE       1059
#define IDC_AC_AUDIO_ADAPTER            1060
#define IDC_AC_PCM                      1062
#define IDC_AC_XADPCM                   1063
#define IDC_AC_UNKNOWN_CODEC            1064
#define IDC_EE_CONFOUNDER               1065
#define IDC_EE_HDDKEY                   1066
#define IDC_EE_XBOX_REGION              1067
#define IDC_EE_SERIAL_NUMBER            1068
#define IDC_EE_MAC_ADDRESS              1069
#define IDC_EE_ONLINE_KEY               1070
#define IDC_EE_AVREGION                 1071
#define IDC_EE_LANGUAGE                 1072
#define IDC_EE_AVSETTINGS               1073
#define IDC_EE_AUDIOSETTINGS            1074
#define IDC_EE_GAME_PRTL_CRTL           1075
#define IDC_EE_PRTL_PASS                1076
#define IDC_EE_MOVIE_PRTL_CRTL          1077
#define IDC_EE_DVDREGION                1078
#define IDC_EE_ACCEPT                   1079
#define IDC_EE_CANCEL                   1080
#define IDC_EE_RESET                    1081
#define IDC_EE_PAL60HZ                  1082
#define IDC_EE_480P                     1083
#define IDC_EE_720P                     1084
#define IDC_EE_1080I                    1085
#define IDC_XBOX_PORT_0                 1158
#define IDC_HOST_NOTCONNECT_0_0         1159
#define IDC_HOST_XINPUT_0_0             1160
#define IDC_HOST_XINPUT_0_1             1161
#define IDC_HOST_XINPUT_0_2             1162
#define IDC_HOST_XINPUT_0_3             1163
#define IDC_HOST_DINPUT_0_0             1164
#define IDC_HOST_VIRTUAL_SBC_0_0        1165
#define IDC_XBOX_PORT_1                 1166
#define IDC_HOST_NOTCONNECT_1_0         1167
#define IDC_HOST_XINPUT_1_0             1168
#define IDC_HOST_XINPUT_1_1             1169
#define IDC_HOST_XINPUT_1_2             1170
#define IDC_HOST_XINPUT_1_3             1171
#define IDC_HOST_DINPUT_1_0             1172
#define IDC_HOST_VIRTUAL_SBC_1_0        1173
#define IDC_XBOX_PORT_2                 1174
#define IDC_HOST_NOTCONNECT_2_0         1175
#define IDC_HOST_XINPUT_2_0             1176
#define IDC_HOST_XINPUT_2_1             1177
#define IDC_HOST_XINPUT_2_2             1178
#define IDC_HOST_XINPUT_2_3             1179
#define IDC_HOST_DINPUT_2_0             1180
#define IDC_HOST_VIRTUAL_SBC_2_0        1181
#define IDC_XBOX_PORT_3                 1182
#define IDC_HOST_NOTCONNECT_3_0         1183
#define IDC_HOST_XINPUT_3_0             1184
#define IDC_HOST_XINPUT_3_1             1185
#define IDC_HOST_XINPUT_3_2             1186
#define IDC_HOST_XINPUT_3_3             1187
#define IDC_HOST_DINPUT_3_0             1188
#define IDC_HOST_VIRTUAL_SBC_3_0        1189
#define IDC_HOST_APPLY                  1190
#define IDC_HOST_CANCEL                 1191
#define IDC_LEFTBLOCK                   1200
#define IDC_LEFTBLOCK2                  1201
#define IDC_RIGHTBLOCK                  1202
#define IDC_GEAR_LEVER                  1203
#define IDC_GEAR_0                      1204
#define IDC_GEAR_1                      1205
#define IDC_GEAR_2                      1206
#define IDC_GEAR_3                      1207
#define IDC_GEAR_4                      1208
#define IDC_GEAR_5                      1209
#define IDC_GEAR_R                      1210
#define IDC_ROTATION_LEVER              1211
#define IDC_TXT_ROTATION_LEVER          1212
#define IDC_VT_LOCATION_MEASUREMENT     1213
#define IDC_BUFFER_MATERIAL             1214
#define IDC_FUEL_FLOW_RATE              1215
#define IDC_OXYGEN_SUPPLY_SYSTEM        1216
#define IDC_FILT_CONTROL_SYSTEM         1217
#define IDC_PB_EJECT                    1218
#define IDC_PB_COCKPIT_HATCH            1219
#define IDC_PB_IGNITION                 1220
#define IDC_PB_START                    1221
#define IDC_PB_GEARLEVER_5              1222
#define IDC_PB_GEARLEVER_1              1223
#define IDC_PB_GEARLEVER_2              1224
#define IDC_PB_GEARLEVER_3              1225
#define IDC_PB_GEARLEVER_4              1226
#define IDC_PB_GEARLEVER_N              1227
#define IDC_PB_GEARLEVER_R              1228
#define IDC_PB_COM5                     1229
#define IDC_PB_COM1                     1230
#define IDC_PB_COM2                     1231
#define IDC_PB_COM3                     1232
#define IDC_PB_COM4                     1233
#define IDC_PB_WASHING                  1234
#define IDC_PB_MAIN_WEAPON_CONTROL      1235
#define IDC_PB_EXTINGUISHER             1236
#define IDC_PB_SUB                      1237
#define IDC_PB_SUB_WEAPON_CONTROL       1237
#define IDC_PB_CHAFF                    1238
#define IDC_PB_MAGAZINE_CHANGE          1239
#define IDC_PB_FUNC1                    1240
#define IDC_PB_FUNC2                    1241
#define IDC_PB_FUNC3                    1242
#define IDC_PB_TANK_DETACH              1243
#define IDC_PB_OVERRIDE                 1244
#define IDC_PB_NIGHT_SCOPE              1245
#define IDC_PB_FSS                      1246
#define IDC_PB_MANIPULATOR              1247
#define IDC_PB_LINE_COLOR_CHANGE        1248
#define IDC_PB_OPEN_CLOSE               1249
#define IDC_PB_MAP_ZOOM_IN_OUT          1250
#define IDC_PB_ZOOM_IN                  1251
#define IDC_PB_ZOOM_OUT                 1252
#define IDC_PB_MODE_SELECT              1253
#define IDC_PB_SUB_MONITOR_MODE_SELECT  1254
#define IDC_RADIO_TD0                   1255
#define IDC_RADIO_TD1                   1256
#define IDC_RADIO_TD2                   1257
#define IDC_RADIO_TD3                   1258
#define IDC_RADIO_TD4                   1259
#define IDC_RADIO_TD5                   1260
#define IDC_RADIO_TD6                   1261
#define IDC_RADIO_TD7                   1262
#define IDC_RADIO_TD8                   1263
#define IDC_RADIO_TD9                   1264
#define IDC_RADIO_TD10                  1265
#define IDC_RADIO_TD11                  1266
#define IDC_RADIO_TD12                  1267
#define IDC_PB_VT_LOCATION_MEASUREMENT  1268
#define IDC_PB_OXYGEN_SUPPLY_SYSTEM     1269
#define IDC_PB_BUFFER_MATERIAL          1270
#define IDC_PB_VT_LOCATION_MEASUREMENT4 1271
#define IDC_PB_FILT_CONTROL_SYSTEM      1272
#define ID_FILE_EXIT                    40005
#define ID_HELP_ABOUT                   40008
#define ID_EMULATION_START              40009
#define ID_FILE_OPEN_XBE                40013
#define ID_FILE_CLOSE_XBE               40014
#define ID_FILE_OPEN_DASHBOARD          40015
#define ID_HELP_HOMEPAGE                40019
#define ID_FILE_SAVEXBEFILE             40021
#define ID_FILE_SAVEXBEFILEAS           40022
#define ID_EDIT_LOGOBITMAP_EXPORT       40025
#define ID_EDIT_LOGOBITMAP_IMPORT       40026
#define ID_EDIT_PATCH_ALLOW64MB         40027
#define ID_EDIT_PATCH_DEBUGMODE         40031
#define ID_EMULATION_DEBUGOUTPUTGUI_CONSOLE 40035
#define ID_EMULATION_DEBUGOUTPUTGUI_FILE 40036
#define ID_EMULATION_DEBUGOUTPUTKERNEL_CONSOLE 40037
#define ID_EMULATION_DEBUGOUTPUTKERNEL_FILE 40038
#define ID_EMULATION_LLE_APU            40039
#define ID_EMULATION_LLE_GPU            40040
#define ID_EMULATION_LLE_JIT            40041
#define ID_SETTINGS_CONFIG_CONTROLLER   40046
#define ID_SETTINGS_CONFIG_VIDEO        40047
#define ID_SETTINGS_CONFIG_AUDIO        40048
#define ID_SETTINGS_CONFIG_EEPROM       40049
#define ID_FILE_RXBE_0                  40050
#define ID_FILE_RXBE_1                  40051
#define ID_FILE_RXBE_2                  40052
#define ID_FILE_RXBE_3                  40053
#define ID_FILE_RXBE_4                  40054
#define ID_FILE_RXBE_5                  40055
#define ID_FILE_RXBE_6                  40056
#define ID_FILE_RXBE_7                  40057
#define ID_FILE_RXBE_8                  40058
#define ID_FILE_RXBE_9                  40059
#define ID_EDIT_DUMPXBEINFOTO_FILE      40071
#define ID_EDIT_DUMPXBEINFOTO_DEBUGCONSOLE 40072
#define ID_EMULATION_STOP               40082
#define ID_SETTINGS_CACHE               40083
#define ID_CACHE_CLEARHLECACHE_ALL      40084
#define ID_CACHE_CLEARHLECACHE_CURRENT  40085
#define ID_SETTINGS_XINPUT              40086
#define ID_SETTINGS_HACKS               40088
#define ID_HACKS_DISABLEPIXELSHADERS    40089
#define ID_LED                          40090
#define ID_SETTINGS_INITIALIZE          40091
#define ID_EMULATION_STARTDEBUGGER      40092
#define ID_FPS                          40096
#define ID_HACKS_UNCAPFRAMERATE         40097
#define ID_HACKS_RUNXBOXTHREADSONALLCORES 40098
#define ID_HACKS_SKIPRDTSCPATCHING      40099
#define ID_HACKS_SCALEVIEWPORT          40100
#define ID_SETTINGS_CONFIG_XBOX_CONTROLLER_MAPPING 40101
#define ID_HACKS_RENDERDIRECTLYTOHOSTBACKBUFFER 40102
#define ID_HACKS_SPEEDHACKS             40103
#define ID_SETTINGS_CONFIG_DLOCCUSTOM   40104
#define ID_SETTINGS_CONFIG_DLOCAPPDATA  40105
#define ID_SETTINGS_CONFIG_DLOCCURDIR   40106
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         40107
#define _APS_NEXT_CONTROL_VALUE         1256
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
