name: Release Artifacts

on:
  push:
    branches: develop

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]
    steps:
      - uses: actions/checkout@master
      - name: Generate cmake files
        run: |
          git submodule update --init --recursive --force
          mkdir build && cd build
          cmake .. -G "Visual Studio 16 2019" -A Win32
      - name: Build
        run: cmake --build build/ --config ${{ matrix.configuration }}
      - name: Organize artifact files
        shell: bash
        run: |
          mkdir dist
          cp {COPYING,README.md} dist/
          cd build/bin/${{ matrix.configuration }}
          [ "${{ matrix.configuration }}" = "Debug" ] && sdl="SDL2d.dll" || sdl=SDL2.dll; cp {Cxbx.exe,glew32.dll,subhook.dll,$sdl} ../../../dist/
          cp {cxbxr-debugger.exe,capstone.dll,cs_x86.dll} ../../../dist/
      - uses: actions/upload-artifact@master
        with:
          name: CXBX-R-${{ matrix.configuration }}-${{ github.sha }}
          path: dist/
